language: rust
sudo: false

rust:
  - stable
  - nightly
  - 1.8.0
  - 1.9.0
  - beta

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH


script:
  - |
    (
    cd quasi &&
    travis-cargo test -- --features with-syntex &&
    travis-cargo --only nightly test --features "with-syntex unstable-testing" &&
    travis-cargo --only nightly test --features unstable-testing &&
    travis-cargo doc -- --features with-syntex
    )
  - |
    (
    cd quasi_macros &&
    travis-cargo --only nightly build &&
    travis-cargo --only nightly test
    )
  - |
    (
    cd quasi_tests &&
    travis-cargo build &&
    travis-cargo test
    )

after_success:
  - |
    (
    cd quasi_tests &&
    travis-cargo --only stable coveralls --no-sudo
    )

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
